stages:
- "test"
- deploy

before_script:
- pip install wheel tox twine

test-3.5:
  image: python:3.5-stretch
  script:  
  - tox -e py35

test-3.6:
  image: python:3.6-stretch
  script:  
  - tox -e py36

test-3.7:
  image: python:3.7-buster
  script:  
  - tox -e py37

test-3.8:
  image: python:3.8-buster
  script:  
  - tox -e py38

deploy_production:
  stage: deploy
  image: python:3.6-stretch

  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  only:
    - tags
