stages:
- pre-commit
- test
- deploy

before_script:
- pip install wheel tox twine

.test-py36:
  stage: test
  image: python:3.6-buster

.test-py37:
  stage: test
  image: python:3.7-buster

.test-py38:
  stage: test
  image: python:3.8-buster

.test-py39:
  stage: test
  image: python:3.9-buster

pre-commit-check:
  stage: pre-commit
  image: python:3.8-buster
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

test-36-django22:
  extends: .test-py36
  script:
  - tox -e py36-django22

test-36-django31:
  extends: .test-py36
  script:
  - tox -e py36-django31

test-36-django32:
  extends: .test-py36
  script:
  - tox -e py36-django32

test-37-django22:
  extends: .test-py37
  script:
  - tox -e py37-django22

test-37-django31:
  extends: .test-py37
  script:
  - tox -e py37-django31

test-37-django32:
  extends: .test-py37
  script:
  - tox -e py37-django32

test-38-django22:
  extends: .test-py38
  script:
  - tox -e py38-django22

test-38-django31:
  extends: .test-py38
  script:
  - tox -e py38-django31

test-38-django32:
  extends: .test-py38
  script:
  - tox -e py38-django32

test-39-django22:
  extends: .test-py39
  script:
  - tox -e py39-django22

test-39-django31:
  extends: .test-py39
  script:
  - tox -e py39-django31

test-39-django32:
  extends: .test-py39
  script:
  - tox -e py39-django32

deploy-pypi:
  stage: deploy
  image: python:3.6-stretch

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  rules:
    - if: $CI_COMMIT_TAG
