stages:
- pre-commit
- gitlab
- test
- deploy

include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml

before_script:
- pip install wheel tox twine

pre-commit-check:
  stage: pre-commit
  image: python:3.10-bullseye
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

sast:
  stage: gitlab
  before_script: []

dependency_scanning:
  stage: gitlab
  before_script:
  - apt-get update && apt-get install redis-server libmariadb-dev -y
  - redis-server --daemonize yes
  - python -V
  - pip install wheel tox

.test-py36:
  stage: test
  image: python:3.6-bullseye
  artifacts:
  when: always
  reports:
    cobertura: coverage.xml

.test-py37:
  stage: test
  image: python:3.7-bullseye
  artifacts:
  when: always
  reports:
    cobertura: coverage.xml

.test-py38:
  stage: test
  image: python:3.8-bullseye
  artifacts:
  when: always
  reports:
    cobertura: coverage.xml

.test-py39:
  stage: test
  image: python:3.9-bullseye
  artifacts:
  when: always
  reports:
    cobertura: coverage.xml

.test-py310:
  stage: test
  image: python:3.10-bullseye
  artifacts:
  when: always
  reports:
    cobertura: coverage.xml

test-docs:
  stage: test
  image: python:3.10-bullseye
  script:
  - tox -e docs

test-36-django22:
  extends: .test-py36
  script:
  - tox -e py36-django22


test-36-django32:
  extends: .test-py36
  script:
  - tox -e py36-django32

test-37-django22:
  extends: .test-py37
  script:
  - tox -e py37-django22

test-37-django32:
  extends: .test-py37
  script:
  - tox -e py37-django32

test-38-django22:
  extends: .test-py38
  script:
  - tox -e py38-django22

test-38-django32:
  extends: .test-py38
  script:
  - tox -e py38-django32

test-38-django40:
  extends: .test-py38
  script:
  - tox -e py38-django40

test-39-django22:
  extends: .test-py39
  script:
  - tox -e py39-django22

test-39-django32:
  extends: .test-py39
  script:
  - tox -e py39-django32

test-39-django40:
  extends: .test-py39
  script:
  - tox -e py39-django40

test-310-django32:
  extends: .test-py310
  script:
  - tox -e py310-django32

test-310-django40:
  extends: .test-py310
  script:
  - tox -e py310-django40

deploy-pypi:
  stage: deploy
  image: python:3.10-bullseye

  before_script:
    - pip install twine

  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

  rules:
    - if: $CI_COMMIT_TAG
