# -*- coding: UTF-8 -*-
"""
DO NOT EDIT THIS FILE

This settings file contains everything needed for Alliance Auth projects to function.
It gets overwritten by the 'allianceauth update' command.
If you wish to make changes, overload the setting in your project's settings file (local.py).
"""

INSTALLED_APPS = [
    'django',
    'django.contrib.auth',
    'esi',
]

SECRET_KEY = "wow I'm a really bad default secret key"

ESI_SSO_CLIENT_ID = 'test-dummy'
ESI_SSO_CLIENT_SECRET = 'test-dummy'
ESI_SSO_CALLBACK_URL = 'http://localhost:8000'


